name: noteshare
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0' # Sesuaikan dengan versi SDK Anda

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  provider: ^6.0.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  intl: ^0.20.2
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/Logo.png
  android: true
  ios: true

  android_12:
    image: assets/Logo.png
    icon_background_color: "#FFFFFF"

  web:
    image: assets/Logo.png
    color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/